# Generated by Django 3.2.5 on 2021-07-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-02-14'),
            preserve_default=False,
        ),
    ]
